/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#783200",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "surface-dim": "#d4dcd5",
        "primary-fixed": "#6ffbbe",
        "on-tertiary-container": "#00367a",
        "on-secondary-container": "#5c2400",
        "surface": "#f4fbf4",
        "on-surface": "#161d19",
        "secondary-fixed": "#ffdbca",
        "surface-tint": "#006c49",
        "background": "#f4fbf4",
        "tertiary-fixed-dim": "#adc6ff",
        "tertiary-container": "#71a1ff",
        "tertiary-fixed": "#d8e2ff",
        "secondary": "#9d4300",
        "on-tertiary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#001a42",
        "surface-container-low": "#eef6ee",
        "on-secondary-fixed": "#341100",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005236",
        "outline": "#6c7a71",
        "on-surface-variant": "#3c4a42",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#00422b",
        "surface-variant": "#dde4dd",
        "surface-container-high": "#e3eae3",
        "on-background": "#161d19",
        "primary-container": "#10b981",
        "outline-variant": "#bbcabf",
        "inverse-primary": "#4edea3",
        "surface-bright": "#f4fbf4",
        "inverse-surface": "#2b322d",
        "on-primary-fixed": "#002113",
        "surface-container": "#e8f0e9",
        "inverse-on-surface": "#ebf3eb",
        "secondary-fixed-dim": "#ffb690",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dde4dd",
        "primary": "#006c49",
        "secondary-container": "#fd761a",
        "tertiary": "#005ac2",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "3xl": "64px",
        "2xl": "48px",
        "md": "16px",
        "sm": "8px",
        "xl": "32px",
        "unit": "4px",
        "xs": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400"}],
        "title-md": ["18px", {"lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600"}],
        "mono-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
